# Generated by Django 5.1.1 on 2024-09-17 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_dt",
                    models.DateTimeField(auto_now=True, verbose_name="갱신일시"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="거래 금액",
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="거래 후 잔액",
                    ),
                ),
                (
                    "transaction_info",
                    models.CharField(
                        choices=[("DEPOSIT", "입금"), ("WITHDRAWAL", "출금")],
                        max_length=255,
                        verbose_name="거래 내용",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("CASH", "현금"),
                            ("TRANSFER", "계좌이체"),
                            ("AUTO_TRANSFER", "자동이체"),
                            ("CARD", "카드결제"),
                        ],
                        max_length=20,
                        verbose_name="거래 유형",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(max_length=20, verbose_name="결제 방식"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                        verbose_name="계좌",
                    ),
                ),
            ],
            options={
                "verbose_name": "거래 내역",
                "verbose_name_plural": "거래 내역들",
            },
        ),
    ]
