# Generated by Django 5.1.1 on 2024-09-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "created_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_dt",
                    models.DateTimeField(auto_now=True, verbose_name="갱신일시"),
                ),
                (
                    "id",
                    models.CharField(
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                        verbose_name="고유ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="이메일"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=128, null=True, verbose_name="비밀번호"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, null=True, verbose_name="이름"),
                ),
                (
                    "nickname",
                    models.CharField(max_length=100, null=True, verbose_name="닉네임"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="전화번호"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="스태프 여부"),
                ),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="관리자 여부"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="활성화 여부"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="마지막 로그인"
                    ),
                ),
                (
                    "login_type",
                    models.CharField(
                        choices=[
                            ("kakao", "카카오"),
                            ("email", "이메일"),
                            ("admin", "관리자"),
                        ],
                        max_length=15,
                        verbose_name="로그인 타입",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자들",
            },
        ),
    ]
