# Generated by Django 5.1.1 on 2024-09-17 04:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_dt",
                    models.DateTimeField(auto_now=True, verbose_name="갱신일시"),
                ),
                (
                    "account_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="계좌번호"
                    ),
                ),
                (
                    "bank_code",
                    models.CharField(
                        choices=[
                            ("KAKAOBANK", "카카오뱅크"),
                            ("KOOKMIN", "국민은행"),
                            ("NH", "농협은행"),
                            ("IBK", "기업은행"),
                            ("WOORI", "우리은행"),
                            ("SHINHAN", "신한은행"),
                        ],
                        max_length=50,
                        verbose_name="은행 코드",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("SAVINGS", "저축계좌"),
                            ("CHECKING", "입출금계좌"),
                            ("INVESTMENT", "투자계좌"),
                            ("LOAN", "대출계좌"),
                            ("OVERDRAFT", "마이너스계좌"),
                        ],
                        max_length=100,
                        verbose_name="계좌 종류",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="잔액",
                    ),
                ),
            ],
            options={
                "verbose_name": "계좌",
                "verbose_name_plural": "계좌들",
            },
        ),
    ]
