# Generated by Django 5.1.1 on 2024-09-13 03:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterbank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_num', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('account_type', models.CharField(max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('bank_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterbank.masterbank', to_field='bank_code')),
            ],
        ),
    ]
